services:
  - type: web
    name: hamily-health-ai
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: xxxx
      - key: JWT_SECRET
        value: xxxx
      - key: GEMINI_API_KEY
        value: xxxx
